apiVersion: checkpoint.devsisters.com/v1
kind: MutatingRule
metadata:
  name: mutate-and-validate-namespace-name-cute
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["namespaces"]
    operations: ["CREATE"]
  code: |
    const request = getRequest();
    const name = request.object.metadata.name;
    if (!name.startsWith("owo-")) {
      deny("That name is not cute.");
    } else if (!name.endsWith("-uwu")) {
      allowAndMutate([{op: "replace", path: "/metadata/name", value: `${name}-uwu`}]);
    }
