apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "checkpoint.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "checkpoint.fullname" . }}-cert
  commonName: {{ printf "%s-webhook" (include "checkpoint.fullname" .) }}
  dnsNames:
    - {{ printf "%s-webhook.%s" (include "checkpoint.fullname" .) .Release.Namespace }}
    - {{ printf "%s-webhook.%s.svc" (include "checkpoint.fullname" .) .Release.Namespace }}
  isCA: true
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: {{ include "checkpoint.issuerName" . }}
    kind: Issuer
