apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoint-controller
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "checkpoint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "checkpoint.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "checkpoint.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: CONF_SERVICE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: CONF_SERVICE_NAME
          value: checkpoint-controller-service
        - name: CONF_SERVICE_PORT
          value: "{{ .Values.service.port }}"
        - name: CONF_CERT_PATH
          value: /tmp/cert/cert.pem
        - name: CONF_KEY_PATH
          value: /tmp/cert/key.pem
        - name: CONF_CA_BUNDLE
          valueFrom:
            secretKeyRef:
              name: {{ include "checkpoint.fullname" . }}-cert
              key: cert.pem
        volumeMounts:
        - name: certs
          mountPath: /tmp/cert
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: {{ include "checkpoint.fullname" . }}-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
