apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoint-controller
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "checkpoint.selectorLabels.controller" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "checkpoint.selectorLabels.controller" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "checkpoint.fullname" . }}-controller"
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.controller.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/checkpoint-controller"]
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: info
        - name: CONF_SERVICE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: CONF_SERVICE_NAME
          value: checkpoint-controller-service
        - name: CONF_SERVICE_PORT
          value: "{{ .Values.service.port }}"
        - name: CONF_CA_BUNDLE
          valueFrom:
            secretKeyRef:
              name: {{ include "checkpoint.fullname" . }}-cert
              key: cert.pem
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoint-webhook
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "checkpoint.selectorLabels.webhook" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webhook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "checkpoint.selectorLabels.webhook" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "checkpoint.fullname" . }}-webhook"
      securityContext:
        {{- toYaml .Values.webhook.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.webhook.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/checkpoint-webhook"]
        ports:
        - containerPort: 3000
        resources:
          {{- toYaml .Values.webhook.resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: info
        - name: CONF_CERT_PATH
          value: /tmp/cert/cert.pem
        - name: CONF_KEY_PATH
          value: /tmp/cert/key.pem
        volumeMounts:
        - name: certs
          mountPath: /tmp/cert
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: {{ include "checkpoint.fullname" . }}-cert
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
