{{- $ca := genCA "admission-controller-ca" 3650 }}
{{- $cn := printf "%s-webhook" (include "checkpoint.fullname" .) }}
{{- $altName1 := printf "%s-webhook.%s" (include "checkpoint.fullname" .) .Release.Namespace }}
{{- $altName2 := printf "%s-webhook.%s.svc" (include "checkpoint.fullname" .) .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "checkpoint.fullname" . }}-cert
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
type: Opaque
data:
  cert.pem: {{ b64enc $cert.Cert }}
  key.pem: {{ b64enc $cert.Key }}
