apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "checkpoint.fullname" . }}-controller"
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "checkpoint.fullname" . }}-controller"
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["checkpoint.devsisters.com"]
  resources: ["validatingrules", "mutatingrules"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "checkpoint.fullname" . }}-controller"
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "checkpoint.fullname" . }}-controller"
subjects:
- kind: ServiceAccount
  name: "{{ include "checkpoint.fullname" . }}-controller"
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "checkpoint.fullname" . }}-webhook"
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
  {{- with .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "checkpoint.fullname" . }}-webhook"
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
rules:
- apiGroups: ["checkpoint.devsisters.com"]
  resources: ["validatingrules", "mutatingrules"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "checkpoint.fullname" . }}-webhook"
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "checkpoint.fullname" . }}-webhook"
subjects:
- kind: ServiceAccount
  name: "{{ include "checkpoint.fullname" . }}-webhook"
  namespace: {{ .Release.Namespace }}
