apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkpoint.fullname" . }}-webhook
  labels:
    {{- include "checkpoint.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.webhook.service.port }}
      targetPort: 3000
  selector:
    {{- include "checkpoint.selectorLabels.webhook" . | nindent 4 }}
