apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-08-24T00:00:00Z"
  name: block
  resourceVersion: "0"
  uid: 00000000-0000-0000-0000-000000000000
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
