apiVersion: checkpoint.devsisters.com/v1
kind: MutatingRule
metadata:
  name: mutate-namespace-name-cute-with-jsonpatch
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["namespaces"]
    operations: ["CREATE"]
  code: |
    request = ...
    if request.object.metadata.name:sub(-4) ~= "-uwu" then
      newObject = deepCopy(request.object)
      newObject.metadata.name = request.object.metadata.name .. "-uwu"
      patch = jsonPatchDiff(request.object, newObject)
      return nil, patch
    end
