apiVersion: checkpoint.devsisters.com/v1
kind: MutatingRule
metadata:
  name: mutate-namespace-name-cute
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["namespaces"]
    operations: ["CREATE"]
  code: |
    request = ...
    name = request.object.metadata.name
    if name:sub(-4) ~= "-uwu" then
      return nil, {{op="replace", path="/metadata/name", value=name .. "-uwu"}}
    end
