apiVersion: checkpoint.devsisters.com/v1
kind: ValidatingRule
metadata:
  name: disallow-wildcard-resources
spec:
  objectRules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    apiVersions: ["*"]
    resources: ["roles", "clusterroles"]
    operations: ["CREATE", "UPDATE"]
  code: |
    const request = getRequest();

    for (const rule of request.object.rules) {
      for (const resource of rule.resources) {
        if (resource.includes("*")) {
          deny("Role should not contain wildcard resource");
        }
      }
    }
