apiVersion: checkpoint.devsisters.com/v1
kind: ValidatingRule
metadata:
  name: disallow-default-namespace
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["*"]
    operations: ["CREATE"]
    scope: "Namespaced"
  code: |
    const request = getRequest();

    if (request.namespace === "default") {
      deny("`default` namespace is not allowed");
    }
