apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkpoint-validatingrule-namespace-must-have-unique-annotation
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkpoint-validatingrule-namespace-must-have-unique-annotation
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkpoint-validatingrule-namespace-must-have-unique-annotation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkpoint-validatingrule-namespace-must-have-unique-annotation
subjects:
- kind: ServiceAccount
  name: checkpoint-validatingrule-namespace-must-have-unique-annotation
  namespace: default
---
apiVersion: checkpoint.devsisters.com/v1
kind: ValidatingRule
metadata:
  name: namespace-must-have-unique-annotation
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["namespaces"]
    operations: ["CREATE"]
  serviceAccount:
    namespace: default
    name: checkpoint-validatingrule-namespace-must-have-unique-annotation
  code: |
    request = ...
    requestedNamespaceUniqueAnnotation = (request.object.metadata.annotations or {})["unique"]

    namespaces = kubeList({group="", version="v1", kind="Namespace"}).items

    for _, namespace in namespaces do
      uniqueAnnotation = (namespace.metadata.annotations or {})["unique"]

      if uniqueAnnotation ~= nil and requestedNamespaceUniqueAnnotation == uniqueAnnotation then
        return "Requested namespace has a not unique `unique` annotation"
      end
    end
