apiVersion: checkpoint.devsisters.com/v1
kind: ValidatingRule
metadata:
  name: namespace-must-have-unique-annotation
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["namespaces"]
    operations: ["CREATE"]
  code: |
    requested_namespace_unique_annotation = (request.object.metadata.annotations or {})["unique"]

    namespaces = kube_list({group="", version="v1", kind="Namespace"}).items

    for _, namespace in namespaces do
      unique_annotation = (namespace.metadata.annotations or {})["unique"]

      if unique_annotation ~= nil and requested_namespace_unique_annotation == unique_annotation then
        return "Requested namespace has a not unique `unique` annotation"
      end
    end
