apiVersion: checkpoint.devsisters.com/v1
kind: ValidatingRule
metadata:
  name: whitelisting-image-registries
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["pods"]
    operations: ["CREATE"]
  code: |
    -- Config
    allowedRegistries = {"docker.io", "k8s.gcr.io"}

    -- Check image of containers, returns nil if validation was passed
    function checkContainers(containers)
      local container
      for _, container in pairs(containers) do
        local registry = getRegistry(container.image)
        if not contains(allowedRegistries, registry) then
          return "Image registry `" .. registry .. "` is not in the white list"
        end
      end
    end

    -- Get registry from image path
    function getRegistry(image)
      local _, index = string.find(image, "/")
      if index == nil then
        return "docker.io"
      else
        return string.sub(image, 1, index - 1)
      end
    end
 
    -- Check if `array` contains `value`
    function contains(array, value)
      local element
      for _, element in pairs(array) do
        if element == value then
          return true
        end
      end
      return false
    end
 

    request = ...
    if request.object.spec.initContainers ~= nil then
      result = checkContainers(request.object.spec.initContainers)
      if result ~= nil then
        return result
      end
    end

    result = checkContainers(request.object.spec.containers)
    if result ~= nil then
      return result
    end
