apiVersion: checkpoint.devsisters.com/v1
kind: MutatingRule
metadata:
  name: add-ttl-to-jobs
spec:
  objectRules:
  - apiGroups: ["batch"]
    apiVersions: ["*"]
    resources: ["jobs"]
    operations: ["CREATE"]
  code: |
    // Config
    const ttlSecondsAfterFinished = 600;

    function main(request) {
      // Skip if ownerReference is specified
      const ownerReferences = request.object.metadata.ownerReferences;
      if (ownerReferences != null && ownerReferences.length > 0) {
        allow();
        return;
      }
      // Skip if ttlSecondsAfterFinished is already specified
      if (request.object.spec.ttlSecondsAfterFinished != null) {
        allow();
        return;
      }

      const newObject = jsonCopy(request.object);
      newObject.spec.ttlSecondsAfterFinished = ttlSecondsAfterFinished;
      const diff = jsonPatchDiff(request.object, newObject);
      allowAndMutate(diff);
    }

    const request = getRequest();
    main(request);
