apiVersion: checkpoint.devsisters.com/v1
kind: MutatingRule
metadata:
  name: mutate-namespace-name-cute
spec:
  objectRules:
  - apiGroups: [""]
    apiVersions: ["*"]
    resources: ["namespaces"]
    operations: ["CREATE"]
  code: |
    request = ...
    if request.name:sub(-4) ~= "-uwu" then
      new_name = request.name .. "-uwu"
      return nil, {{op="replace", path="/metadata/name", value=new_name}}
    end
