name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build container image
      run: docker build . -t ghcr.io/devsisters/checkpoint:${{ github.sha }}
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push container image
      if: github.ref == 'refs/heads/main'
      # TODO: Push with tag
      run: docker push ghcr.io/devsisters/checkpoint:${{ github.sha }}
