name: clippy

on:
  push:
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.71.1
      with:
        components: clippy
    - run: cargo clippy --no-deps --all-targets -- -D warnings
