name: crdgen

on:
  pull_request:

jobs:
  crdgen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.71.1
    - uses: Swatinem/rust-cache@v2
    - name: Check crdgen diff
      run: cargo run --bin crdgen | diff helm/templates/crds/customresourcedefinition.yaml -
