name: release-image

on:
  push:
    tags:
    - "v*"

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: ecr-login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      with:
        registry-type: public
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ steps.ecr-login.outputs.registry }}/devsisters/checkpoint
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
        flavor:
          latest=auto
    - uses: actions/checkout@v3
    - name: Build and push container image to AWS ECR
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        cache-to: type=gha,mode=max
        cache-from: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
