name: release

on:
  push:
    tags:
    - "chart-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: actions/checkout@v3
    - name: Bulid and push Helm chart to S3
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git
          helm repo add devsisters s3://devsisters-public-helm-charts
          helm package helm
          helm s3 push *.tgz devsisters --relative
