name: release-image

on:
  push:
    branches:
      - "test-arm-build"

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: actions/checkout@v4
    - name: Build and push container image to AWS ECR
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        cache-to: type=gha,mode=max
        cache-from: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
