name: rustfmt

on:
  push:
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.71.1
      with:
        components: rustfmt
    - run: cargo fmt --check
