name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.71.1
    - uses: Swatinem/rust-cache@v2
    - run: cargo test

  example-testcases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@1.71.1
    - uses: Swatinem/rust-cache@v2
    - name: Run example testcases
      run: cargo run --bin checkpoint -- test $(find -type f -iname testcase.yaml)
